# Default config.yml for Engine
keen:
  allow_tracking: true
  project_id: 530a932c36bf5a2d23000000
  write_key: ed91795fd2a7e88c5de09a31c982edf3c242b90cbdce6f5e375ec3200d1ee75d0efeba6597a277d51579dde3a61ceafc2a9e902925c18f6d9a410c4db78f388dcc2518f4ba48f9789ae5fea7f0ba2cce8f3b8999a8965d7f7148383d0184a497be09369d8cb6da315e3cd2ad01cc93fb

spells:
  explosion:
    class: com.gmail.spraetz.spells.Explosion
    reagents:
      - reagent: SULPHUR
        quantity: 1
    settings:
      radius: 2
      damage_multiplier: 1
  fire_ball:
    class: com.gmail.spraetz.spells.FireBall
    reagents:
      - reagent: COAL
        quantity: 2
    settings:
      radius: 1
      damage_multiplier: 1
      ignite_radius: 3
      fire_ticks: 100
  lightning_bolt:
    class: com.gmail.spraetz.spells.LightningBolt
    reagents:
      - reagent: GOLD_INGOT
        quantity: 1
  teleport:
    class: com.gmail.spraetz.spells.Teleport
    reagents:
      - reagent: REDSTONE
        quantity: 3
  stone_wall:
    class: com.gmail.spraetz.spells.Wall
    reagents:
      - reagent: COBBLESTONE
        quantity: 8
    settings:
      material: BEDROCK
      height: 5
      width: 4
      minimum_ticks: 80
      maximum_ticks: 120
  heal_self:
    class: com.gmail.spraetz.spells.HealSelf
    reagents:
      - reagent: APPLE
        quantity: 1
      - reagent: GLOWSTONE_DUST
        quantity: 1
    settings:
      percent_of_max_health: 30
  heal_other:
    class: com.gmail.spraetz.spells.HealOther
    reagents:
      - reagent: SPECKLED_MELON
        quantity: 1
      - reagent: GLOWSTONE_DUST
        quantity: 1
    settings:
      percent_of_max_health: 30
  recall:
    class: com.gmail.spraetz.spells.Recall
    reagents:
      - reagent: EYE_OF_ENDER
        quantity: 1
  flight:
    class: com.gmail.spraetz.spells.Flight
    reagents:
      - reagent: FEATHER
        quantity: 1
    settings:
      ticks: 400
  push:
    class: com.gmail.spraetz.spells.Push
    reagents:
      - reagent: WHEAT
        quantity: 1
    settings:
      knockback: 2.0
      up_force: 0.5
      max_up_force: 1.0