# Default config.yml for Engine
keen:
  project_id: 5305558fd97b8560ca00000f
  write_key: B98D4F3392827FA8046945C7767FCD0F

spells:
  explosion:
    class: Explosion
    reagents:
      - reagent: SULPHUR
        quantity: 2
    settings:
      radius: 3
  fire_blast:
    class: FireBlast
    reagents:
      - reagent: FLINT_AND_STEEL
        quantity: 2
    settings:
      radius: 1
  lightning_bolt:
    class: LightningBolt
    reagents:
      - reagent: GOLD_INGOT
        quantity: 1
  teleport:
    class: Teleport
    reagents:
      - reagent: REDSTONE_DUST
        quantity: 3
  stone_wall:
    class: StoneWall
    reagents:
      - reagent: STONE
        quantity: 8
    settings:
      height: 5
      width: 4
      minimum_ticks: 80
      maximum_ticks: 120
  heal_self:
    class: HealSelf
    reagents:
      - reagent: DIAMOND
        quantity: 1
    settings:
      percent_of_max_health: 30