name: MineCraftSpells
version: 2.2
main: com.gmail.spraetz.plugin.MineCraftSpells
depend: [ProtocolLib]

commands:
  charge:
    description: Imbues a book with magic powers
    usage: /<command> spell [charges]
    permission: player
    permission-message: You don't have <permission>
  particle:
    description: Used to test particle effects
    usage: /<command> effectName
    permission: player
    permission-message: You don't have <permission>
  sound:
    description: Used to test sound effects
    usage: /<command> effectName
    permission: player
    permission-message: You don't have <permission>
  launch:
    description: Used to test launch effects
    usage: /<command> projectile
    permission: player
    permission-message: You don't have <permission>

permissions:
  player:
    description: Default permission set for all players.
    default: true